name: pytest3 
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - python=3.7
  - numpy
  - pip
  - matplotlib
  - pandas
  - ipython
  - jupyterlab
  - pip:
    - natsort
    - sklearn
    - pytest
prefix: /Users/taziy/anaconda3/envs/pytest3
